### ISSUE TITLE
brew error when running more than once

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-vim#11]
Hey @JHaals, I'm seeing the same problem of the vim package failing after the first time. Running `sudo -E -u user brew switch vim 7.3.976` manually has the same error that @michaeldauria in https://github.com/boxen/puppet-vim/issues/6 has. Is this a problem with the homebrew package?

```
Error: Execution of 'brew switch vim 7.3.976' returned 1: Cleaning /opt/boxen/homebrew/Cellar/vim/7.3.976
Warning: Could not link vim. Unlinking...
Error: Could not symlink file: /opt/boxen/homebrew/Cellar/vim/7.3.976/bin/vimdiff
Target /opt/boxen/homebrew/bin/vimdiff already exists. You may need to delete it.
To force the link and overwrite all other conflicting files, do:
  brew link --overwrite formula_name

To list all files that would be deleted:
  brew link --overwrite --dry-run formula_name

Error: /Stage[main]/Vim/Package[vim]/ensure: change from absent to present failed: Execution of 'brew switch vim 7.3.976' returned 1: Cleaning /opt/boxen/homebrew/Cellar/vim/7.3.976
Warning: Could not link vim. Unlinking...
Error: Could not symlink file: /opt/boxen/homebrew/Cellar/vim/7.3.976/bin/vimdiff
Target /opt/boxen/homebrew/bin/vimdiff already exists. You may need to delete it.
To force the link and overwrite all other conflicting files, do:
  brew link --overwrite formula_name

To list all files that would be deleted:
  brew link --overwrite --dry-run formula_name
```

**Comment by jhaals** [comment]
I'd say it's related to brew since this module only ensures that vim is installed with brew. Have you tried running the
`brew link --overwrite`?

**Comment by seanknox** [comment]
Yup, `brew link --overwrite` runs no problem. So is this a matter of adjusting the brew package?

**Comment by seanknox** [comment]
Hey @JHaals, any ideas what needs to change in puppet-homebrew to fix this error?

**Comment by jhaals** [comment]
I don't know what causes this error. I guess it's trying to upgrade your vim and failing when unlinking the old version. I should raise this in puppet-homebrew or then upstream repo.

**Comment by seanknox** [comment]
FWIW: just reenabled the vim module in Boxen, and I'm no longer seeing this issue.
