### ISSUE TITLE
failure installing mercurial

### ISSUE THREAD

**Issue by nicknovitski** [boxen/puppet-vim#12]
```
Warning: For non-brewed Python, you have to set the PYTHONPATH in order to
find brewed Python modules.
export PYTHONPATH=/opt/boxen/homebrew/lib/python2.7/site-packages:$PYTHONPATH
Warning: For non-brewed Python, you have to set the PYTHONPATH in order to
find brewed Python modules.
export PYTHONPATH=/opt/boxen/homebrew/lib/python2.7/site-packages:$PYTHONPATH

Error: An unsatisfied requirement failed this build.
Error: Could not set 'present' on ensure: Failed running sudo -E -u sidereel /opt/boxen/homebrew/bin/brew install mercurial at 17:/opt/boxen/repo/shared/vim/manifests/init.pp
Error: Could not set 'present' on ensure: Failed running sudo -E -u sidereel /opt/boxen/homebrew/bin/brew install mercurial at 17:/opt/boxen/repo/shared/vim/manifests/init.pp
Wrapped exception:
Failed running sudo -E -u sidereel /opt/boxen/homebrew/bin/brew install mercurial
Error: /Stage[main]/Vim/Package[mercurial]/ensure: change from absent to present failed: Could not set 'present' on ensure: Failed running sudo -E -u sidereel /opt/boxen/homebrew/bin/brew install mercurial at 17:/opt/boxen/repo/shared/vim/manifests/init.pp
```

In order to solve this, I've consistently had to manually install python, and run `pip install docutils`, a python module that mercurial depends on, and which the homebrew package for mercurial cannot automatically install. 

I'm actually confused why mercurial is installed by the module.  A comment in init.pp suggests that there is some requirement which the mercurial package satisfies that the vim package does not...what requirement is that?  Is there some other package with simpler dependencies that would also satisfy it?  Am I screwing up something really obvious? :confused:

**Comment by jhaals** [comment]
the vim package does fetch vim via mercurial, it's stupid but it does.
I discovered the docutils requirement yesterday on new machines, I dont know if the module should install one more weird/stupid dependency.

So the workaround could be

```
package { 'docutils':
  ensure => installed,
  provider => pip
}
```

**Comment by nicknovitski** [comment]
Ohhh! [I see!](https://github.com/mxcl/homebrew/blob/master/Library/Formula/vim.rb)

Could we write our own brew that only fetches and builds a tar.gz file of
some known version?
- Nick Novitski http://nicknovitski.com (stuff i've
  donehttps://github.com/nicknovitski/
  )
