### ISSUE TITLE
Could not locate the pip command

### ISSUE THREAD

**Issue by pedrogimenez** [boxen/puppet-vim#14]
When I do script/boxen, throws this error:

> Error: Could not set 'present' on ensure: Could not locate the pip command. at 28:/opt/boxen/repo/shared/vim/manifests/init.pp
> Error: Could not set 'present' on ensure: Could not locate the pip command. at 28:/opt/boxen/repo/shared/vim/manifests/init.pp
> Wrapped exception:
> Could not locate the pip command.
> Error: /Stage[main]/Vim/Package[docutils]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not locate the pip command. at 28:/opt/boxen/repo/shared/vim/manifests/init.pp

**Comment by am** [comment]
Same here, I'm running a fresh install of boxen in a VM.

**Comment by jhaals** [comment]
OS X pip is "broken" by default. Either install pip via easy_install or install Python via brew.
