### ISSUE TITLE
vim::setup problem

### ISSUE THREAD

**Issue by dieterdemeyer** [boxen/puppet-vim#4]
I'm trying to run your module and I see that `manifests/init.pp` requires `manifests/setup.pp` but it doesn't seem to execute the code when I run it.

Any thoughts ?

**Comment by jhaals** [comment]
try running from version 1.0.2, I did a cleanup.
Any updates on your travis fixes? I would like to add proper CI tests in travis for this module.

**Comment by dieterdemeyer** [comment]
I'll give it a try and let you know..

I updated my boxen repos and have successful travis builds..
You can take a look at puppet-adium, puppet-intellij and others..
I filed an issue for my adium repo because travis isn't building (my guess is that the webhook isn't configured).

**Comment by jhaals** [comment]
Should be fixed now :)
