### ISSUE TITLE
can't find my .vimrc file

### ISSUE THREAD

**Issue by scottgc** [boxen/puppet-vim#9]
Even though my .vimrc exists when I attempt to add this module I still get file can not be found error. Any advice.

**Comment by jhaals** [comment]
That's strange. The file_line that installs pathogen in .vimrc looks for `File["/Users/${::boxen_user}/.vimrc"]`
Is your home directory somewhere else? I might need to create a parameterized class instead.
Please show me the line where you add your .vimrc via boxen.

**Comment by scottgc** [comment]
The issue is more what have I not tried.

I have used your sample code, tried setting up the .vimrc in advance. Please do not get me wrong, i am sure there is something basic I am missing. I know this is not a help section, but if you could help point me in the direction of either understanding how to set up and use the /manifest/people/${name}.pp or ensure I am adding the right code to my /site.pp to do the following

clone my .dotefiles repo off github which contains a .vimrc
Then uses that .vimrc with my puppet-vim 

What I have setup now that is still not working.

I have manually created a ~/.vimrc
Then I run boxen using puppet-vim, "1.0.3" and have include vim within my site.pp file

This produces the error file /Users/scottgibson-craig/.vimrc not found.

Thanks for your help.

**Comment by jhaals** [comment]
Some instructions at https://github.com/boxen/our-boxen/tree/master/modules/people

I wouldn't add anything personal to site.pp

This should work
`file { "/Users/${boxen_user}/.vimrc":
  ensure => file
}`
